### ISSUE TITLE
Source IP Address

### ISSUE THREAD

**Issue by luischanu** [brichbourg/Multi-Tier-App-Demo#10]
Brantley,

It would be nice if the server page also showed the IP address of the client hitting the web page.  This comes into play when a load balancer is configured between Transparent and Non-Transparent modes, as the source changes depending on the mode.

Keep up the great work!

**Comment by brichbourg** [comment]
Good idea, do you think a link from the server info page that would pop up a window with the data would work?  Or just load a new page entirely. Pops up would be good for this use case but they also get blocked by browsers too. 
I'm thinking at least of of those so the UI doesn't get cluttered on the main area of the app. 
Thoughts?
Sent from my iPhone 

On Mon, Feb 1, 2016 at 5:19 PM -0800, "luischanu" notifications@github.com wrote:

Brantley,

It would be nice if the server page also showed the IP address of the client hitting the web page  This comes into play when a load balancer is configured between Transparent and Non-Transparent modes, as the source changes depending on the mode

Keep up the great work!

**Comment by luischanu** [comment]
Pop-ups aren't good because if you need to refresh the page many times quickly, it's a mess...ok, even 1 time is too many with pop-ups, because then I need to go close them.  :)

I would prefer if it was part of the page drawn, and I don't think it will "clutter up" the page.  I think of clutter as items you don't need, but his IS useful.  You can put another small window either below or above the ones that you currently have, and show the IPv4 / IPv6 address it's coming from.  With the initial setup, it would just show the following info:

Source IPv4 Address
Source Port

Source port would be helpful to verify the LB is maintaining source port as part of it's state.  It should, but good to have a way to confirm.

Luis

**Comment by brichbourg** [comment]
Luis, I think that I got confused.  I was thinking that you wanted a list of IP addresses that have hit the server, but you just want another field, like the IP address of the server displaying in the server info box.

Am I understanding you correctly?  Here is an example of what I am thinking:

![screen shot 2016-02-02 at 10 19 54 pm](https://cloud.githubusercontent.com/assets/9040680/12771938/1bb66bde-c9fb-11e5-9871-e6c345a0e0e2.png)

**Comment by brichbourg** [comment]
For the record, here is the idea that will be implemented
![unknown](https://cloud.githubusercontent.com/assets/9040680/12772903/3cd3781c-ca04-11e5-9fdd-e110c1747ee5.png)

**Comment by brichbourg** [comment]
Added in commit https://github.com/brichbourg/Multi-Tier-App-Demo/commit/2532185e964e1a82b17e4468a41a4f35560c1e16

The X_Forwarded_For functionality needs testing however.  Once I verify that part is working I will close this issue/request.

**Comment by brichbourg** [comment]
I verified the X_Forwarded_For feature works as expected in 0.4.3.
![screen shot 2016-02-15 at 5 40 52 pm](https://cloud.githubusercontent.com/assets/9040680/13062280/5a4f7a6a-d40b-11e5-8d64-bfc6c4a17343.png)
