### ISSUE TITLE
App "Name" In Browser Tab

### ISSUE THREAD

**Issue by luischanu** [brichbourg/Multi-Tier-App-Demo#11]
With many instances open, it's difficult to know which tab relates to what type of connection (i.e. HTTP, HTTPS, etc.), needless to say which server connection.

I'd like to suggest that the name in the tab within the browser be changed from the static "Multi-Tier Web Application" to the following:

<Hostname> / <IPv4 Address> (HTTPS)

<Hostname> would be replaced by the hostname that shows in the page
" / " is literal (Notice the single space on each side)
<IPv4 Address> would be replaced by the VM's IP address
(HTTPS) would only appear if the session is via HTTPS, else it does not appear (not even the "()")

Thank you, and keep up the excellent work!

Sincerely,

Yet another happy customer!

**Comment by luischanu** [comment]
It removed my variables...  They were:

Hostname / IPv4 Address (HTTPS)

Where Hostname and IPv4 Address are variables replaced as described above.

**Comment by brichbourg** [comment]
Feature added in version 0.5.1 via the commit below.

0c04bf9f9b5717a81c09998330275e844fb49d16
