### ISSUE TITLE
sitebuild script

### ISSUE THREAD

**Issue by luischanu** [brichbourg/Multi-Tier-App-Demo#9]
Brantley,

The sitebuild script says "press any key", but I found that not to be the case.  I had to press ENTER, as space did not work.  Just thought I'd let you know.

Luis

**Comment by brichbourg** [comment]
Fixed in commit https://github.com/brichbourg/Multi-Tier-App-Demo/commit/eb05690d95ea5a290de8728726fe3754843d5146
